### ISSUE TITLE
Broken urls in Edit Hint Dialog

### ISSUE THREAD

**Issue by mohit-surana** [marshall62/msadmin#22]
Refreshing the page and trying to open the Edit Hint dialog does not recreate the hint URL for the image thumbnail correctly

Eg. The link shows up as:
http://rose.cs.umass.edu/msadmin/qauth/prob/save/undefinedhint_7358/mvn-conditional.png

Instead of:
http://rose.cs.umass.edu/mathspring/mscontent/html5Probs/qa/problem_1589/hint_7358/mvn-conditional.png

This leads to a 404 in the msadmin tool.

A possibly related issue is that subsequent changes to image placement options are not propagated to the database. It is only reflected if you make the changes the first time you upload / reupload an image.

**Comment by marshall62** [comment]
not sure how to reproduce this error.

**Comment by nishankjain** [comment]
@mohit-surana Does this error still exist or can we close this? If it does, how do I reproduce it?

**Comment by mohit-surana** [comment]
Tested it. It looks like this has been taken care of. Closing.
