### ISSUE TITLE
Preview” is launching MathSpring on woj, ROSE. Change to point to AWS.

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/msadmin#27]
The “Preview” is launching MathSpring on woj, and on rose. This has to be changed to point to AWS: http://ec2-34-239-246-100.compute-1.amazonaws.com

**Comment by mohit-surana** [comment]
One line change to be made [here](https://github.com/marshall62/msadmin/blob/master/msadmin/templates/msadmin/qa/qauth_edit.html#L94)

The authoring tool goes to a URL of the following form:
http://tutor.mathspring.org/woj/WoAdmin?action=AdminGetQuickAuthSkeleton&probId=%s&teacherId=-1&reload=true&zoom=1

This needs to be replaced with something like:
http://ec2-34-239-246-100.compute-1.amazonaws.com/woj/WoAdmin?action=AdminGetQuickAuthSkeleton&probId=%s&teacherId=-1&reload=true&zoom=1

Currently, this end point does not work. Will have to get in touch with Neeraj regarding how to point to the new endpoint.
