### ISSUE TITLE
“Replace main figure” with a figure uploaded in the hint, does not work. 

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/msadmin#28]
“Replace main figure” with a figure uploaded in the hint, does not work. It does not replace the main figure of the problem with the one indicated/uploaded in the hint. (Ivon, 10/4/18)

**Comment by IvonArroyo** [comment]
MIGHT REQUIRE COORDINATION between Neeraj (WPI) and Mohit (UMASS).

**Comment by IvonArroyo** [comment]
Mohit, I found a math problem that has this issue.
Take a look at Hint1 for this problem, then "preview".
http://rose.cs.umass.edu/msadmin/qauth/prob/edit/1675/#

**Comment by mohit-surana** [comment]
I did some digging up and I think I understand why this is happening:
- If we replace the problem figure, we add the name of the image to imageURL.
- If an image is inside the hint body, we don't update the imageURL field in the db.
- If we add an image that is inside the hint body, and change it to replace problem figure later on, then the imageURL field in the db does not get updated.

These problems currently have this issue:
```
select h.id, h.problemId, h.imageFileID, pmf.filename
from hint h, problemmediafile pmf
where h.placement=1 and h.imageFileID=pmf.id and imageURL="";
```

Will implement the fix shortly.

**Comment by IvonArroyo** [comment]
Here is another problem with the same issue to test:
http://rose.cs.umass.edu/msadmin/qauth/prob/edit/1867/#

**Comment by mohit-surana** [comment]
Code fix has been pushed. Stale values in the DB yet to be cleaned.

**Comment by mohit-surana** [comment]
DB values have also been fixed [programmatically](https://github.com/marshall62/msadmin/commit/5f764f5593c50ee49fa8fd5d3f1d5040644d4cb2).
