### ISSUE TITLE
List of Tables that MSAdmin accesses

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/msadmin#32]
Generate a list of tables that MSAdmin accesses? 
Maybe create a new schema.

**Comment by mohit-surana** [comment]
Shared the list of tables via mail. If information is required at the field granularity, please let me know.

**Comment by IvonArroyo** [comment]
Mohit, we only need a list of tables that the "Math Problems" section of the MSAdmin accesses and alters. Can you please re-send just those tables?

**Comment by IvonArroyo** [comment]
We cannot move any problems across databases until we get this list. --Ivon

**Comment by mohit-surana** [comment]
List has been sent.
